### ISSUE TITLE
Select options HTML attributes

### ISSUE THREAD

**Issue by baasha** [contributte/forms-bootstrap#24]
Hi guys,
is there any chance to support options rendering attributes set via new [setOptionAttribute()](https://doc.nette.org/en/3.0/form-rendering#toc-html-attributes) method (since Nette Forms 3.0.4) in the future ?

Quoted from Nette doc:

```php
$form->addSelect('colors', 'Colors:', $colors)
	->setOptionAttribute('style:', $styles);
```
Renders:

```html
<select name="colors">
	<option value="r" style="background:red">red</option>
	<option value="g" style="background:green">green</option>
	<option value="b">blue</option>
</select>
```

Thanks in advance.

**Comment by dakorpar** [comment]
@baasha sure, I'll add it!

**Comment by dakorpar** [comment]
@baasha PR #26 should solve it, but for now without colon or questionmark support, I need to do a bit of refactoring to use nette option generation, but for that I need to catch some time... for now if urgent U can use this branch dev-allow-option-atrtributes
but this most likely won't be merged in, on next release it will probably be supported to use it natively from nette...
most probably new release will come in next week or two.

**Comment by baasha** [comment]
> @baasha PR #26 should solve it, but for now without colon or questionmark support, I need to do a bit of refactoring to use nette option generation, but for that I need to catch some time... for now if urgent U can use this branch dev-allow-option-atrtributes
> but this most likely won't be merged in, on next release it will probably be supported to use it natively from nette...
> most probably new release will come in next week or two.

Thank you, you are great. 👏 
It is not urgent, I know we all have to do other things to pay bills first, but thanks anyway for your enthusiasm. 👍

**Comment by dakorpar** [comment]
@baasha #28 solves this, it's also a BC break, but I consider it more a bugfix because until now translator hasn't been used in setItems and on setPrompt check this on v0.3 (current master alias) but stable version will be released somewhere tomorrow when I make sure on my projects no problems detected...

**Comment by dakorpar** [comment]
@baasha new version released closing this, open new issue if U see something not correct!

**Comment by baasha** [comment]
Works like a charm. Good job, thank you.
