### ISSUE TITLE
TextArea - label must be of the type string or null

### ISSUE THREAD

**Issue by patriksuchovsky** [contributte/forms-bootstrap#30]
In form, I want to put nette Html object into label in TextArea (addTextArea method), but I'm getting this error:
`TypeError: Argument 1 passed to Contributte\FormsBootstrap\Inputs\TextAreaInput::__construct() must be of the type string or null, object given, called in __path/vendor/contributte/forms-bootstrap/src/Traits/BootstrapContainerTrait.php on line 259 in __path/vendor/contributte/forms-bootstrap/src/Inputs/TextAreaInput.php:19`

In TextAreaInput.php in __construct is type of $label `?string`.

For example in addText it works properly.

**Comment by dakorpar** [comment]
@patriksuchovsky  solved with #31 it will be merged in few minutes and new version released
thanks for reporting!
