### ISSUE TITLE
PHPUnit -> Nette Tester

### ISSUE THREAD

**Issue by petrparolek** [contributte/forms-bootstrap#38]
Hi @dakorpar could convert tests from PHPUnit to Nette Tester based on RFC https://github.com/contributte/contributte/issues/34 please?:  @f3l1x asked me to make it but I think you will be ten times faster and more effective than me. Taks very much.

**Comment by dakorpar** [comment]
No way, if this goes to nette tester I'm out of it. I don't like nette tester and it's a deal breaker for me. I allways and everywhere use phpunit.

**Comment by dakorpar** [comment]
@petrparolek nope. Tests remain on phpunit.
