### ISSUE TITLE
CheckBox - label must be of the type string or null - same as #30

### ISSUE THREAD

**Issue by patriksuchovsky** [contributte/forms-bootstrap#44]
In form, I want to put nette Html object into label in TextArea (addTextArea method), but I'm getting this error:
`TypeError: Argument 3 passed to Contributte\FormsBootstrap\Inputs\CheckboxInput::makeCheckbox() must be of the type string or null, object given`

It's same as my last issue #30

Thanks.

**Comment by dakorpar** [comment]
@patriksuchovsky thanks for reporting,
fixed in fb4aec2268d38a396e06345c62e9458b058fd422
