### ISSUE TITLE
Bootstrap 5

### ISSUE THREAD

**Issue by rpajik** [contributte/forms-bootstrap#47]
Hello,

do you have any plans for support Bootstrap 5 ?
There are some issues ... for example select and checkbox are not working well.

thx

**Comment by dakorpar** [comment]
@rpajik sure, feel free also to send PR, I'm still not using bootstrap 5, it should be an easy upgrade IMHO

**Comment by stanislav-janu** [comment]
@rpajik Support is prepared in PR #53. It wasn't hard to handle. :-)

**Comment by stanislav-janu** [comment]
@dakorpar Hello, is it ok for release?

**Comment by dakorpar** [comment]
Well I'd like to check few stuffs and update to newest nette/forms but running out of time constantly

**Comment by dakorpar** [comment]
@stanislav-janu this is released, thanks!
