### ISSUE TITLE
Bad Group & Row rendering

### ISSUE THREAD

**Issue by yosieu** [contributte/forms-bootstrap#55]
Hello, 

you have an error in BootstrapForm rendering. If is defined group witch contains BootstrapRow, then is rendered multiple duplicity rows with their contents and at the end is rendered Group. 

Error is in class BootstrapRow, where you don't make $this-setOption(rendered, true);

Thanks for fix it. 

Example:

       $row1 = $this->addRow("line1");
        $row1->addCell(6)
                ->addSelect('category', 'Kategorie', $this->category_repository->getIdNameList())
                    ->setHtmlAttribute("class", "selectpicker form-control")
                    ->setHtmlAttribute("title", "Vyberte ...")
                    ->setRequired(true)
                    ->getLabelPrototype()
                        ->setClass('required');

        $row1->addCell(6)
                ->addSelect('edition', 'Ročník', Edition::getList())
                    ->setHtmlAttribute("class", "selectpicker form-control")
                    ->setHtmlAttribute("title", "Vyberte ...")
                    ->setRequired(true)
                    ->getLabelPrototype()
                        ->setClass('required');

        $group1 = $this->addGroup('Group 1', false)
                        ->add([$row1]);

![image](https://user-images.githubusercontent.com/2078754/139706250-42ca4485-91ea-4390-b5f5-b57375454a14.png)

**Comment by dakorpar** [comment]
@yosieu  thanks for reporting this is fixed in master, I'll release 0.5.1 in few minutes....
