### ISSUE TITLE
Uprava rendereru

### ISSUE THREAD

**Issue by Pepino483** [contributte/forms-bootstrap#67]
Zdravím, 

bylo by možné upravit následující řádek https://github.com/contributte/forms-bootstrap/blob/9708a54e509504ffffea1e5d9527f0d0812fd506/src/BootstrapRenderer.php#L471 za něco jako:
`if ($control instanceof CustomControl) {`

kde `CustomControl` by byla jen jednoduchá třída např:
```
class CustomControl implements IComponent, Control
{
	use SmartObject;
	use FakeControlTrait;
....
}
````

Nově by od ní dědila `BootstrapRow`.

Řeším momentálně situaci, že potřebuju do formuláře mezi políčka dostat něco nestandartního a přitom ho vykreslit přes `{control form}`. Aktuálně jsem to vyřešil, že mám třídu, která dědí od `BootstrapRow` z důvodů aby se zavolalo:
https://github.com/contributte/forms-bootstrap/blob/9708a54e509504ffffea1e5d9527f0d0812fd506/src/BootstrapRenderer.php#L472

PS: Jako bonus bych byl i pro upravení
https://github.com/contributte/forms-bootstrap/blob/9708a54e509504ffffea1e5d9527f0d0812fd506/src/BootstrapRenderer.php#L474 aby šlo nějakým způsobem ovlivnit u viditelných prvků, zda se zavolá `$pairHtml = $this->renderControl($control);` nebo `$pairHtml = $this->renderPair($control);`

**Comment by Pepino483** [comment]
Vytvořil jsem k tomu PR https://github.com/contributte/forms-bootstrap/pull/68

**Comment by dakorpar** [comment]
use english.
