### ISSUE TITLE
add cell with COLUMNS_AUTO doesn't work

### ISSUE THREAD

**Issue by pytelCZ** [contributte/forms-bootstrap#70]
Because in BootstrapRow class in addCell function there is $numOfColumns defined as int (and COLUMNS_AUTO  is set as null)

**Comment by dakorpar** [comment]
This should be fixed now, can U try on dev-master or ^0.6 to confirm? I'll release version after you confirm

**Comment by pytelCZ** [comment]
perfect, fixed
