### ISSUE TITLE
nette/forms version 3.1.9 doesnt exists anymore

### ISSUE THREAD

**Issue by BigOHenry** [contributte/forms-bootstrap#78]
Last version of **contributte/forms-bootstrap 0.5.5** requires **nette/forms 3.1.9**, but this version does not exists anymore. It was fine yesterday.

**Comment by BigOHenry** [comment]
https://github.com/nette/forms/issues/297

**Comment by dakorpar** [comment]
@BigOHenry I believe dg added 3.1.9 tag again so it should all be ok

**Comment by BigOHenry** [comment]
Its OK. Closing. Thx
