### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by rendix2** [contributte/forms-bootstrap#87]
Hi, 

I updated from "contributte/forms-bootstrap": "^0.5.6" to "contributte/forms-bootstrap": "^0.6.0" . I also updated from "nette/forms": "^3.1" to "nette/forms": "^v3.1.12" 

Log from composer: 

 `# composer update contributte/forms-bootstrap -W
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 4 updates, 0 removals
  - Upgrading contributte/forms-bootstrap (v0.5.7 => v0.6)
  - Upgrading nette/component-model (v3.0.3 => v3.1.0)
  - Upgrading nette/forms (v3.1.11 => v3.1.12)
  - Upgrading nette/http (v3.2.3 => v3.3.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 4 updates, 0 removals
  - Downloading nette/forms (v3.1.12)
  - Downloading contributte/forms-bootstrap (v0.6)
  - Upgrading nette/http (v3.2.3 => v3.3.0): Extracting archive
  - Upgrading nette/component-model (v3.0.3 => v3.1.0): Extracting archive
  - Upgrading nette/forms (v3.1.11 => v3.1.12): Extracting archive
  - Upgrading contributte/forms-bootstrap (v0.5.7 => v0.6): Extracting archive`

Now there is compile error.

![image](https://github.com/contributte/forms-bootstrap/assets/8470476/0c88602e-12b4-44b2-b39b-20189bd89f46)

Can be this fixed please?

**Comment by dakorpar** [comment]
Added compatibility with nette/component-model 3.1

**Comment by rendix2** [comment]
Thank you fox fix. It works nicely again :)
