### ISSUE TITLE
floating label to bootstrap 5

### ISSUE THREAD

**Issue by RodrigoAliotti** [contributte/forms-bootstrap#98]
- with command: activeFloatLabel() -- after render mode may put label floating

put files with changes to use - zipped.
[BootstrapFrmRnd.zip](https://github.com/user-attachments/files/16060171/BootstrapFrmRnd.zip)

contains the files changed:
   BootstrapRenderer.php
   BootstrapForm.php

**Comment by dakorpar** [comment]
@RodrigoAliotti can U send normal pull request?

**Comment by RodrigoAliotti** [comment]
I do'nt have permission to push in github to project:
remote: Permission to contributte/forms-bootstrap.git denied to RodrigoAliotti.
fatal: unable to access 'https://github.com/contributte/forms-bootstrap.git/': The requested URL returned error: 403

**Comment by dakorpar** [comment]
you need to fork project first, create branch on your fork and then you can create PR here from it.

**Comment by RodrigoAliotti** [comment]
thanks i will try.

**Comment by RodrigoAliotti** [comment]
I have success on generate the floating label branch, thanks.

**Comment by RodrigoAliotti** [comment]
finally published with branch.

**Comment by RodrigoAliotti** [comment]
Finally published with branch. Thanks by help.
